!!python/object/new:easydict.EasyDict
state:
  train_2d: false
  no_eval: true
  finetune: false
  partial_train: null
  epochs: 1
  checkpoint_frequency: 10
  batch_size: 8
  dropout: 0.0
  learning_rate: 0.0002
  weight_decay: 0.01
  lr_decay: 0.99
  backbone: PoseMamba
  maxlen: 27
  dim_feat: 64
  mlp_ratio: 2
  depth: 8
  att_fuse: true
  data_root: /home/hayepc/3D-bicycle-pose-estimation/data/posemamba_sequences/PoseMamba_f27s100
  subset_list: &id001
  - BICYCLE
  dt_file: unused_for_bicycle.pkl
  clip_len: 27
  data_stride: 9
  rootrel: true
  sample_stride: 1
  num_joints: 18
  no_conf: true
  gt_2d: true
  lambda_3d_velocity: 20.0
  lambda_scale: 0.5
  lambda_lv: 0.0
  lambda_lg: 0.0
  lambda_a: 0.0
  lambda_av: 0.0
  lambda_3dw: 0.0
  lambda_3d: 1.0
  lambda_diff: 0.5
  synthetic: true
  flip: false
  mask_ratio: 0.0
  mask_T_ratio: 0.0
  noise: false
  max_batches: 1
  max_eval_batches: 0
  name: PoseMamba_train_bicycle.generated
dictitems:
  train_2d: false
  no_eval: true
  finetune: false
  partial_train: null
  epochs: 1
  checkpoint_frequency: 10
  batch_size: 8
  dropout: 0.0
  learning_rate: 0.0002
  weight_decay: 0.01
  lr_decay: 0.99
  backbone: PoseMamba
  maxlen: 27
  dim_feat: 64
  mlp_ratio: 2
  depth: 8
  att_fuse: true
  data_root: /home/hayepc/3D-bicycle-pose-estimation/data/posemamba_sequences/PoseMamba_f27s100
  subset_list: *id001
  dt_file: unused_for_bicycle.pkl
  clip_len: 27
  data_stride: 9
  rootrel: true
  sample_stride: 1
  num_joints: 18
  no_conf: true
  gt_2d: true
  lambda_3d_velocity: 20.0
  lambda_scale: 0.5
  lambda_lv: 0.0
  lambda_lg: 0.0
  lambda_a: 0.0
  lambda_av: 0.0
  lambda_3dw: 0.0
  lambda_3d: 1.0
  lambda_diff: 0.5
  synthetic: true
  flip: false
  mask_ratio: 0.0
  mask_T_ratio: 0.0
  noise: false
  max_batches: 1
  max_eval_batches: 0
  name: PoseMamba_train_bicycle.generated
